version: '3.8'

services:
  ngrok:
    build:
      context: ./ngrok
      args:
        TOKEN: "${TOKEN}"
    depends_on:
      - mitmproxy
    environment:
      HOST_NAME: "${HOST_NAME}"
  mitmproxy:
    build: ./mitmproxy
    environment:
      TARGET_PORT: "${TARGET_PORT}"
