version: '3.8'

services:
  ngrok:
    build:
      context: ./ngrok
      args:
        TOKEN: "${TOKEN}"
    env_file: .env
    depends_on:
      - mitmproxy
    environment:
      HOST_NAME: "${HOST_NAME}"
    restart: always
    deploy:
      resources:
        limits:
          memory: 100m
  mitmproxy:
    build: ./mitmproxy
    env_file: .env
    environment:
      TARGET_PORT: "${TARGET_PORT}"
    restart: always
    deploy:
      resources:
        limits:
          memory: 100m
